defmodule Conga.Repo.Migrations.RemoveCommentIdentity do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop_if_exists unique_index(:comments, [:user_id, :post_id, :parent_comment_id],
                     name: "comments_unique_user_comment_and_post_index"
                   )
  end

  def down do
    create unique_index(:comments, [:user_id, :post_id, :parent_comment_id],
             name: "comments_unique_user_comment_and_post_index"
           )
  end
end
