defmodule Conga.Repo.Migrations.PageViewsNew do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      add :page_views, :bigint, default: 0
    end
  end
end
