defmodule Conga.Repo.Migrations.BookmarkCommentRel do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:bookmarks, "bookmarks_post_id_fkey")

    drop constraint(:bookmarks, "bookmarks_user_id_fkey")

    alter table(:bookmarks) do
      add :comment_id,
          references(:comments,
            column: :id,
            name: "bookmarks_comment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )

      modify :user_id,
             references(:users,
               column: :id,
               name: "bookmarks_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE bookmarks alter CONSTRAINT bookmarks_user_id_fkey NOT DEFERRABLE")

    alter table(:bookmarks) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "bookmarks_post_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE bookmarks alter CONSTRAINT bookmarks_post_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:bookmarks, "bookmarks_post_id_fkey")

    alter table(:bookmarks) do
      modify :post_id,
             references(:posts,
               column: :id,
               name: "bookmarks_post_id_fkey",
               type: :uuid,
               prefix: "public"
             )
    end

    drop constraint(:bookmarks, "bookmarks_comment_id_fkey")

    drop constraint(:bookmarks, "bookmarks_user_id_fkey")

    alter table(:bookmarks) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "bookmarks_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      remove :comment_id
    end
  end
end
