defmodule Conga.Repo.Migrations.CommentReviewed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      modify :is_approved, :boolean, default: true
    end
  end

  def down do
    alter table(:comments) do
      modify :is_approved, :boolean, default: false
    end
  end
end
