defmodule Conga.Repo.Migrations.Categories do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:post_categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true

      add :post_id,
          references(:posts,
            column: :id,
            name: "post_categories_post_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          ),
          primary_key: true,
          null: false

      add :category_id, :uuid, null: false, primary_key: true
    end

    create table(:categories, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end

    alter table(:post_categories) do
      modify :category_id,
             references(:categories,
               column: :id,
               name: "post_categories_category_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:categories) do
      add :name, :text, null: false

      add :inserted_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end
  end

  def down do
    alter table(:categories) do
      remove :updated_at
      remove :inserted_at
      remove :name
    end

    drop constraint(:post_categories, "post_categories_category_id_fkey")

    alter table(:post_categories) do
      modify :category_id, :uuid
    end

    drop table(:categories)

    drop constraint(:post_categories, "post_categories_post_id_fkey")

    drop table(:post_categories)
  end
end
