defmodule Conga.Repo.Migrations.RemovePostCategoryId do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:post_categories) do
      remove :id
    end
  end

  def down do
    alter table(:post_categories) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
    end
  end
end
