defmodule Conga.Repo.Migrations.CommentsHasMany do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:comments) do
      add :comment_id,
          references(:comments,
            column: :id,
            name: "comments_comment_id_fkey",
            type: :uuid,
            prefix: "public",
            on_delete: :delete_all
          )
    end
  end

  def down do
    drop constraint(:comments, "comments_comment_id_fkey")

    alter table(:comments) do
      remove :comment_id
    end
  end
end
