defmodule Conga.Repo.Migrations.AllowNilTrueForPostAvatar do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:profiles, "profiles_user_id_fkey")

    alter table(:profiles) do
      modify :avatar, :text, null: true

      modify :user_id,
             references(:users,
               column: :id,
               name: "profiles_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    execute("ALTER TABLE profiles alter CONSTRAINT profiles_user_id_fkey NOT DEFERRABLE")
  end

  def down do
    drop constraint(:profiles, "profiles_user_id_fkey")

    alter table(:profiles) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "profiles_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :avatar, :text, null: false
    end
  end
end
