defmodule Conga.Repo.Migrations.IdentityPostCategory do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create unique_index(:post_categories, [:post_id, :category_id],
             name: "post_categories_unique_post_category_index"
           )
  end

  def down do
    drop_if_exists unique_index(:post_categories, [:post_id, :category_id],
                     name: "post_categories_unique_post_category_index"
                   )
  end
end
