defmodule Conga.Repo.Migrations.ReadingTimeFixed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      remove :reading_time
    end
  end

  def down do
    alter table(:posts) do
      add :reading_time, :bigint, default: 0
    end
  end
end
