defmodule Conga.Repo.Migrations.PostAllowTrueForCategoryPicture do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    drop constraint(:pictures, "pictures_user_id_fkey")

    alter table(:pictures) do
      modify :url, :text, null: true

      modify :user_id,
             references(:users,
               column: :id,
               name: "pictures_user_id_fkey",
               type: :uuid,
               prefix: "public",
               on_delete: :delete_all
             )
    end

    alter table(:categories) do
      modify :name, :text, null: true
    end

    execute("ALTER TABLE pictures alter CONSTRAINT pictures_user_id_fkey NOT DEFERRABLE")
  end

  def down do
    alter table(:categories) do
      modify :name, :text, null: false
    end

    drop constraint(:pictures, "pictures_user_id_fkey")

    alter table(:pictures) do
      modify :user_id,
             references(:users,
               column: :id,
               name: "pictures_user_id_fkey",
               type: :uuid,
               prefix: "public"
             )

      modify :url, :text, null: false
    end
  end
end
