defmodule Conga.Repo.Migrations.PostRemoveCategoryAttribute do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:posts) do
      remove :category
    end
  end

  def down do
    alter table(:posts) do
      add :category, :text, null: false
    end
  end
end
