defmodule Conga.Repo.Migrations.TextToBody do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    rename table(:posts), :text, to: :body

    alter table(:posts) do
      modify :body, :text
    end
  end

  def down do
    alter table(:posts) do
      modify :text, :text
    end

    rename table(:posts), :body, to: :text
  end
end
