defmodule Conga.Repo.Migrations.LikesReviewed do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:likes) do
      remove :status
    end

    create unique_index(:likes, [:user_id, :post_id], name: "likes_unique_user_and_post_index")
  end

  def down do
    drop_if_exists unique_index(:likes, [:user_id, :post_id],
                     name: "likes_unique_user_and_post_index"
                   )

    alter table(:likes) do
      add :status, :boolean, default: false
    end
  end
end
