defmodule Conga.Repo.Migrations.RevertPostAllowTrueForCategoryPicture do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:pictures) do
      modify :url, :text, null: false
    end

    alter table(:categories) do
      modify :name, :text, null: false
    end
  end

  def down do
    alter table(:categories) do
      modify :name, :text, null: true
    end

    alter table(:pictures) do
      modify :url, :text, null: true
    end
  end
end
